# coding: utf-8

"""
    Travel Restrictions

    Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.   # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class DataSources(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            covidDashboardLink = schemas.StrSchema
            healthDepartmentSiteLink = schemas.StrSchema
            governmentSiteLink = schemas.StrSchema
            __annotations__ = {
                "covidDashboardLink": covidDashboardLink,
                "healthDepartmentSiteLink": healthDepartmentSiteLink,
                "governmentSiteLink": governmentSiteLink,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["covidDashboardLink"]) -> MetaOapg.properties.covidDashboardLink: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["healthDepartmentSiteLink"]) -> MetaOapg.properties.healthDepartmentSiteLink: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["governmentSiteLink"]) -> MetaOapg.properties.governmentSiteLink: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["covidDashboardLink", "healthDepartmentSiteLink", "governmentSiteLink", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["covidDashboardLink"]) -> typing.Union[MetaOapg.properties.covidDashboardLink, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["healthDepartmentSiteLink"]) -> typing.Union[MetaOapg.properties.healthDepartmentSiteLink, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["governmentSiteLink"]) -> typing.Union[MetaOapg.properties.governmentSiteLink, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["covidDashboardLink", "healthDepartmentSiteLink", "governmentSiteLink", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        covidDashboardLink: typing.Union[MetaOapg.properties.covidDashboardLink, str, schemas.Unset] = schemas.unset,
        healthDepartmentSiteLink: typing.Union[MetaOapg.properties.healthDepartmentSiteLink, str, schemas.Unset] = schemas.unset,
        governmentSiteLink: typing.Union[MetaOapg.properties.governmentSiteLink, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DataSources':
        return super().__new__(
            cls,
            *_args,
            covidDashboardLink=covidDashboardLink,
            healthDepartmentSiteLink=healthDepartmentSiteLink,
            governmentSiteLink=governmentSiteLink,
            _configuration=_configuration,
            **kwargs,
        )
