# coding: utf-8

"""
    Travel Restrictions

    Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.   # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class DeclarationDocuments(
    schemas.ComposedSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        
        class all_of_1(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    isRequired = schemas.StrSchema
                    healthDocumentationLink = schemas.StrSchema
                    travelDocumentationLink = schemas.StrSchema
                    text = schemas.StrSchema
                    lastUpdate = schemas.StrSchema
                    
                    
                    class healthInsurance(
                        schemas.ListSchema
                    ):
                    
                    
                        class MetaOapg:
                            
                            @staticmethod
                            def items() -> typing.Type['HealthInsuranceModality']:
                                return HealthInsuranceModality
                    
                        def __new__(
                            cls,
                            _arg: typing.Union[typing.Tuple['HealthInsuranceModality'], typing.List['HealthInsuranceModality']],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                        ) -> 'healthInsurance':
                            return super().__new__(
                                cls,
                                _arg,
                                _configuration=_configuration,
                            )
                    
                        def __getitem__(self, i: int) -> 'HealthInsuranceModality':
                            return super().__getitem__(i)
                    __annotations__ = {
                        "isRequired": isRequired,
                        "healthDocumentationLink": healthDocumentationLink,
                        "travelDocumentationLink": travelDocumentationLink,
                        "text": text,
                        "lastUpdate": lastUpdate,
                        "healthInsurance": healthInsurance,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["isRequired"]) -> MetaOapg.properties.isRequired: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["healthDocumentationLink"]) -> MetaOapg.properties.healthDocumentationLink: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["travelDocumentationLink"]) -> MetaOapg.properties.travelDocumentationLink: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["text"]) -> MetaOapg.properties.text: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["lastUpdate"]) -> MetaOapg.properties.lastUpdate: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["healthInsurance"]) -> MetaOapg.properties.healthInsurance: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["isRequired", "healthDocumentationLink", "travelDocumentationLink", "text", "lastUpdate", "healthInsurance", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["isRequired"]) -> typing.Union[MetaOapg.properties.isRequired, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["healthDocumentationLink"]) -> typing.Union[MetaOapg.properties.healthDocumentationLink, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["travelDocumentationLink"]) -> typing.Union[MetaOapg.properties.travelDocumentationLink, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["text"]) -> typing.Union[MetaOapg.properties.text, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["lastUpdate"]) -> typing.Union[MetaOapg.properties.lastUpdate, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["healthInsurance"]) -> typing.Union[MetaOapg.properties.healthInsurance, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["isRequired", "healthDocumentationLink", "travelDocumentationLink", "text", "lastUpdate", "healthInsurance", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                isRequired: typing.Union[MetaOapg.properties.isRequired, str, schemas.Unset] = schemas.unset,
                healthDocumentationLink: typing.Union[MetaOapg.properties.healthDocumentationLink, str, schemas.Unset] = schemas.unset,
                travelDocumentationLink: typing.Union[MetaOapg.properties.travelDocumentationLink, str, schemas.Unset] = schemas.unset,
                text: typing.Union[MetaOapg.properties.text, str, schemas.Unset] = schemas.unset,
                lastUpdate: typing.Union[MetaOapg.properties.lastUpdate, str, schemas.Unset] = schemas.unset,
                healthInsurance: typing.Union[MetaOapg.properties.healthInsurance, list, tuple, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_1':
                return super().__new__(
                    cls,
                    *_args,
                    isRequired=isRequired,
                    healthDocumentationLink=healthDocumentationLink,
                    travelDocumentationLink=travelDocumentationLink,
                    text=text,
                    lastUpdate=lastUpdate,
                    healthInsurance=healthInsurance,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                DatedInformation,
                cls.all_of_1,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DeclarationDocuments':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.dated_information import DatedInformation
from openapi_client.model.health_insurance_modality import HealthInsuranceModality
