# coding: utf-8

"""
    Travel Restrictions

    Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.   # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class Expiration(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            expiresAfter = schemas.StrSchema
            referenceDateTime = schemas.StrSchema
            __annotations__ = {
                "expiresAfter": expiresAfter,
                "referenceDateTime": referenceDateTime,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expiresAfter"]) -> MetaOapg.properties.expiresAfter: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["referenceDateTime"]) -> MetaOapg.properties.referenceDateTime: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["expiresAfter", "referenceDateTime", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expiresAfter"]) -> typing.Union[MetaOapg.properties.expiresAfter, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["referenceDateTime"]) -> typing.Union[MetaOapg.properties.referenceDateTime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["expiresAfter", "referenceDateTime", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        expiresAfter: typing.Union[MetaOapg.properties.expiresAfter, str, schemas.Unset] = schemas.unset,
        referenceDateTime: typing.Union[MetaOapg.properties.referenceDateTime, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Expiration':
        return super().__new__(
            cls,
            *_args,
            expiresAfter=expiresAfter,
            referenceDateTime=referenceDateTime,
            _configuration=_configuration,
            **kwargs,
        )
