# coding: utf-8

"""
    Travel Restrictions

    Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.   # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class Transportation(
    schemas.ComposedSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        
        class all_of_1(
            schemas.DictSchema
        ):
        
        
            class MetaOapg:
                
                class properties:
                    
                    
                    class transportationType(
                        schemas.EnumBase,
                        schemas.StrSchema
                    ):
                        
                        @schemas.classproperty
                        def FLIGHT(cls):
                            return cls("FLIGHT")
                        
                        @schemas.classproperty
                        def CAR(cls):
                            return cls("CAR")
                        
                        @schemas.classproperty
                        def BUS(cls):
                            return cls("BUS")
                    isBanned = schemas.StrSchema
                    throughDate = schemas.StrSchema
                    __annotations__ = {
                        "transportationType": transportationType,
                        "isBanned": isBanned,
                        "throughDate": throughDate,
                    }
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["transportationType"]) -> MetaOapg.properties.transportationType: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["isBanned"]) -> MetaOapg.properties.isBanned: ...
            
            @typing.overload
            def __getitem__(self, name: typing_extensions.Literal["throughDate"]) -> MetaOapg.properties.throughDate: ...
            
            @typing.overload
            def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
            
            def __getitem__(self, name: typing.Union[typing_extensions.Literal["transportationType", "isBanned", "throughDate", ], str]):
                # dict_instance[name] accessor
                return super().__getitem__(name)
            
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["transportationType"]) -> typing.Union[MetaOapg.properties.transportationType, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["isBanned"]) -> typing.Union[MetaOapg.properties.isBanned, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: typing_extensions.Literal["throughDate"]) -> typing.Union[MetaOapg.properties.throughDate, schemas.Unset]: ...
            
            @typing.overload
            def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
            
            def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["transportationType", "isBanned", "throughDate", ], str]):
                return super().get_item_oapg(name)
            
        
            def __new__(
                cls,
                *_args: typing.Union[dict, frozendict.frozendict, ],
                transportationType: typing.Union[MetaOapg.properties.transportationType, str, schemas.Unset] = schemas.unset,
                isBanned: typing.Union[MetaOapg.properties.isBanned, str, schemas.Unset] = schemas.unset,
                throughDate: typing.Union[MetaOapg.properties.throughDate, str, schemas.Unset] = schemas.unset,
                _configuration: typing.Optional[schemas.Configuration] = None,
                **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
            ) -> 'all_of_1':
                return super().__new__(
                    cls,
                    *_args,
                    transportationType=transportationType,
                    isBanned=isBanned,
                    throughDate=throughDate,
                    _configuration=_configuration,
                    **kwargs,
                )
        
        @classmethod
        @functools.lru_cache()
        def all_of(cls):
            # we need this here to make our import statements work
            # we must store _composed_schemas in here so the code is only run
            # when we invoke this method. If we kept this at the class
            # level we would get an error because the class level
            # code would be run when this module is imported, and these composed
            # classes don't exist yet because their module has not finished
            # loading
            return [
                DatedInformation,
                cls.all_of_1,
            ]


    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Transportation':
        return super().__new__(
            cls,
            *_args,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.dated_information import DatedInformation
