# coding: utf-8

"""
    Travel Restrictions

    Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.   # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class TravelTestConditionsAndRules(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            travel_phases_ = schemas.StrSchema
            
            
            class scenarios(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['TravelTestSceanrio']:
                        return TravelTestSceanrio
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['TravelTestSceanrio'], typing.List['TravelTestSceanrio']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'scenarios':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'TravelTestSceanrio':
                    return super().__getitem__(i)
            __annotations__ = {
                "travelPhases ": travel_phases_,
                "scenarios": scenarios,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["travelPhases "]) -> MetaOapg.properties.travel_phases_: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scenarios"]) -> MetaOapg.properties.scenarios: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["travelPhases ", "scenarios", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["travelPhases "]) -> typing.Union[MetaOapg.properties.travel_phases_, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scenarios"]) -> typing.Union[MetaOapg.properties.scenarios, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["travelPhases ", "scenarios", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        scenarios: typing.Union[MetaOapg.properties.scenarios, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TravelTestConditionsAndRules':
        return super().__new__(
            cls,
            *_args,
            scenarios=scenarios,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.travel_test_sceanrio import TravelTestSceanrio
