# coding: utf-8

"""
    Travel Restrictions

    Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)** for more information on how to generate an access token.   # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class TravelTestCondition(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def traveller() -> typing.Type['TravelTestTravellerCondition']:
                return TravelTestTravellerCondition
        
            @staticmethod
            def trip() -> typing.Type['TravelTestTripCondition']:
                return TravelTestTripCondition
            textualScenario = schemas.StrSchema
            __annotations__ = {
                "traveller": traveller,
                "trip": trip,
                "textualScenario": textualScenario,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["traveller"]) -> 'TravelTestTravellerCondition': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["trip"]) -> 'TravelTestTripCondition': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["textualScenario"]) -> MetaOapg.properties.textualScenario: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["traveller", "trip", "textualScenario", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["traveller"]) -> typing.Union['TravelTestTravellerCondition', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["trip"]) -> typing.Union['TravelTestTripCondition', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["textualScenario"]) -> typing.Union[MetaOapg.properties.textualScenario, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["traveller", "trip", "textualScenario", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        traveller: typing.Union['TravelTestTravellerCondition', schemas.Unset] = schemas.unset,
        trip: typing.Union['TravelTestTripCondition', schemas.Unset] = schemas.unset,
        textualScenario: typing.Union[MetaOapg.properties.textualScenario, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TravelTestCondition':
        return super().__new__(
            cls,
            *_args,
            traveller=traveller,
            trip=trip,
            textualScenario=textualScenario,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.travel_test_traveller_condition import TravelTestTravellerCondition
from openapi_client.model.travel_test_trip_condition import TravelTestTripCondition
